config/routes.rb
Rails.application.routes.draw do

  root 'weathers#index'

  resources :current_locations, only: [:new, :create, :show]

  resources :city_states, only: [:new, :create, :show]

  resources :zipcode, only: [:new, :create, :show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/city_states_controller.rb
class CityStatesController < ApplicationController

  def new
    @location = Location.new
    render :_new
  end

  def create
    @location = Location.new(destination: params[:destination], zipcode: params[:zipcode], city_state: true, current_location: params[:current_location])
    if @location.save
      if request.xhr?
        render :_show, layout: false, locals:{location: @location}
      else
        redirect_to city_state_path
      end
    else
      if request.xhr?
        @errors = Error.full_messages
        redirect_to :_new, layout: false, locals:{location: @location, errors: @errors}
      else
        @errors = Error.full_messages
        redirect_to(:new)
      end
    end
  end

  def show
    @location = location.find(params[:id])
    if request.xhr?
      render :_show, layout: false, locals:{location: @location}
    else
      render :show
    end
  end

end

app/controllers/current_locations_controller.rb
class CurrentLocationsController < ApplicationController

def new
    @location = Location.new
    render :_new
  end

  def create
    @location = Location.new(destination: params[:destination], zipcode: params[:zipcode], city_state: params[:city_state], current_location: true)
    if @location.save
      if request.xhr?
        render :_show, layout: false, locals:{location: @location}
      else
        redirect_to city_state_path
      end
    else
      if request.xhr?
        @errors = Error.full_messages
        redirect_to :_new, layout: false, locals:{location: @location, errors: @errors}
      else
        @errors = Error.full_messages
        redirect_to(:new)
      end
    end
  end

  def show
    @location = location.find(params[:id])
    if request.xhr?
      render :_show, layout: false, locals:{location: @location}
    else
      render :show
    end
  end

end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController

  def index
    render :index
  end

end

app/controllers/zipcode_controller.rb
class ZipcodeController < ApplicationController

def new
    @location = Location.new
    render :_new
  end

  def create
    @location = Location.new(destination: params[:destination], zipcode: true, city_state: params[:city_state], current_location: params[:current_location])
    if @location.save
      if request.xhr?
        render :_show, layout: false, locals:{location: @location}
      else
        redirect_to city_state_path
      end
    else
      if request.xhr?
        @errors = Error.full_messages
        redirect_to :_new, layout: false, locals:{location: @location, errors: @errors}
      else
        @errors = Error.full_messages
        redirect_to(:new)
      end
    end
  end

  def show
    @location = location.find(params[:id])
    if request.xhr?
      render :_show, layout: false, locals:{location: @location}
    else
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_states_helper.rb
module CityStatesHelper
end

app/helpers/current_locations_helper.rb
module CurrentLocationsHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/helpers/zipcode_helper.rb
module ZipcodeHelper
end

app/views/city_states/_new.html.erb
<div class = "jumbotron center-text">
  <%= form_tag(city_states_path, id: "city_state_form") do %>
    <div>
      <p>City and State:</p>
        <%= text_field_tag('destination', "", class: "search")%>
        <%= hidden_field_tag('city_state', 'true') %>
    </div>
    <% if @errors %>
      <div class = "center error">
        <% @errors.each do |error| %>
          <%= error %>
        <% end %>
      </div>
    <% end %>
    <div class = "center"><%= submit_tag "Search Weather", :id=> "submitButton" %></div>
  <% end %>
</div>

app/views/city_states/_show.html.erb
<div class = "jumbotron center-text">
  <div>
    <h1 id = "city"></h1>
  </div>
    <div class="row">
    <div class="col-md-4">
      <h3>High</h3>
      <p id= "high"></p>
    </div>
    <div class="col-md-4">
      <h3>Current</h3>
      <p id= "current"></p>
    </div>
    <div class="col-md-4">
      <h3>Low</h3>
      <p id= "low"></p>
    </div>
  </div>
  <%= link_to "Search Again", root_path, id: "home" %>
</div>

app/views/city_states/new.html.erb
<div id = "container-fluid">
  <div class = "jumbotron center-text">
    <%= form_tag(city_states_path, id: "city_state_form") do %>
      <div>
        <p>City and State:</p>
          <%= text_field_tag('destination', "", class: "search")%>
          <%= hidden_field_tag('city_state', 'true') %>
      </div>
      <% if @errors %>
        <div class = "center error">
          <% @errors.each do |error| %>
            <%= error %>
          <% end %>
        </div>
      <% end %>
      <div class = "center"><%= submit_tag "Search Weather", :id=> "submitButton" %></div>
    <% end %>
  </div>
</div>

app/views/city_states/show.html.erb
<div id = "container-fluid">
  <div class = "jumbotron center-text">
    <div>
      <h1 id = "city"></h1>
    </div>
      <div class="row">
      <div class="col-md-4">
        <h3>High</h3>
        <p id= "high"></p>
      </div>
      <div class="col-md-4">
        <h3>Current</h3>
        <p id= "current"></p>
      </div>
      <div class="col-md-4">
        <h3>Low</h3>
        <p id= "low"></p>
      </div>
    </div>
    <%= link_to "Search Again", root_path, id: "home" %>
  </div>
</div>

app/views/current_locations/_new.html.erb
<div class = "jumbotron center-text">
  <%= form_tag(city_states_path, id: "current_location_form") do %>
    <div>
      <p>Current Zip Code:</p>
        <%= text_field_tag "destination","value_text", :class => "search"%>
        <%= hidden_field_tag('current_location', 'true') %>
    </div>
    <% if @errors %>
      <div class = "center error">
        <% @errors.each do |error| %>
          <%= error %>
        <% end %>
      </div>
    <% end %>
    <div class = "center"><%= submit_tag "Search Weather", :id=> "submitButton" %></div>
  <% end %>
</div>

app/views/current_locations/_show.html.erb
<div class = "jumbotron center-text">
  <div>
    <h1 id = "city"></h1>
  </div>
    <div class="row">
    <div class="col-md-4">
      <h3>High</h3>
      <p id= "high"></p>
    </div>
    <div class="col-md-4">
      <h3>Current</h3>
      <p id= "current"></p>
    </div>
    <div class="col-md-4">
      <h3>Low</h3>
      <p id= "low"></p>
    </div>
  </div>
  <%= link_to "Search Again", root_path, id: "home" %>
</div>

app/views/current_locations/new.html.erb
<div id = "container-fluid">
  <div class = "jumbotron center-text">
    <%= form_tag(city_states_path, id: "current_location_form") do %>
      <div>
        <p>Current Zip Code:</p>
          <%= text_field_tag "destination","value_text", :class => "search"%>
          <%= hidden_field_tag('current_location', 'true') %>
      </div>
      <% if @errors %>
        <div class = "center error">
          <% @errors.each do |error| %>
            <%= error %>
          <% end %>
        </div>
      <% end %>
      <div class = "center"><%= submit_tag "Search Weather", :id=> "submitButton" %></div>
    <% end %>
  </div>
</div>

app/views/current_locations/show.html.erb
<div id = "container-fluid">
  <div class = "jumbotron center-text">
    <div>
      <h1 id = "city"></h1>
    </div>
      <div class="row">
      <div class="col-md-4">
        <h3>High</h3>
        <p id= "high"></p>
      </div>
      <div class="col-md-4">
        <h3>Current</h3>
        <p id= "current"></p>
      </div>
      <div class="col-md-4">
        <h3>Low</h3>
        <p id= "low"></p>
      </div>
    </div>
    <%= link_to "Search Again", root_path, id: "home" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merlin</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weathers/index.html.erb
<div id = "container-fluid">
  <div class = "jumbotron center-text">
    <h1>Welcome to Weather Wizard</h1>
    <div class="row">
      <div class="col-md-4">
        <p><%= link_to "City And State", new_city_state_path, id: "city_state" %></p>
      </div>
      <div class="col-md-4">
        <p><%= link_to "Zipcode", new_zipcode_path, id: "zipcode" %></p>
      </div>
      <div class="col-md-4">
        <p><%= link_to "Current Location", new_current_location_path, id: "current_location" %></p>
      </div>
    <div class="row">
  </div>
</div>

app/views/zipcode/_new.html.erb
<div class = "jumbotron center-text">
  <%= form_tag(city_states_path, id: "zipcode_form") do %>
    <div>
      <p>Zipcode:</p>
        <%= text_field_tag('destination', "", class: "search")%>
        <%= hidden_field_tag('zipcode', 'true') %>
    </div>
    <% if @errors %>
      <div class = "center error">
        <% @errors.each do |error| %>
          <%= error %>
        <% end %>
      </div>
    <% end %>
    <div class = "center"><%= submit_tag "Search Weather", :id=> "submitButton" %></div>
  <% end %>
</div>

app/views/zipcode/_show.html.erb
  <div class = "jumbotron center-text">
    <div>
      <h1 id = "city"></h1>
    </div>
      <div class="row">
      <div class="col-md-4">
        <h3>High</h3>
        <p id= "high"></p>
      </div>
      <div class="col-md-4">
        <h3>Current</h3>
        <p id= "current"></p>
      </div>
      <div class="col-md-4">
        <h3>Low</h3>
        <p id= "low"></p>
      </div>
    </div>
    <%= link_to "Search Again", root_path, id: "home" %>
  </div>

app/views/zipcode/new.html.erb
<div id = "container-fluid">
  <div class = "jumbotron center-text">
    <%= form_tag(city_states_path, id: "zipcode_form") do %>
      <div>
        <p>Zipcode:</p>
          <%= text_field_tag('destination', "", class: "search")%>
          <%= hidden_field_tag('zipcode', 'true') %>
      </div>
      <% if @errors %>
        <div class = "center error">
          <% @errors.each do |error| %>
            <%= error %>
          <% end %>
        </div>
      <% end %>
      <div class = "center"><%= submit_tag "Search Weather", :id=> "submitButton" %></div>
    <% end %>
  </div>
</div>

app/views/zipcode/show.html.erb
<div id = "container-fluid">
  <div class = "jumbotron center-text">
    <div>
      <h1 id = "city"></h1>
    </div>
      <div class="row">
      <div class="col-md-4">
        <h3>High</h3>
        <p id= "high"></p>
      </div>
      <div class="col-md-4">
        <h3>Current</h3>
        <p id= "current"></p>
      </div>
      <div class="col-md-4">
        <h3>Low</h3>
        <p id= "low"></p>
      </div>
    </div>
    <%= link_to "Search Again", root_path, id: "home" %>
  </div>
</div>